### ISSUE TITLE
Objective-C Example registerTokernizer problem

### ISSUE THREAD

**Issue by runningdemo** [haifengkao/SqliteSubstringSearch#2]
Xcode report symbol error of registerTokenizer in the README Objective-c example. Am I miss something.

Here is my project linked binary:
<img width="754" alt="screen shot 2015-12-17 at 4 33 30 pm" src="https://cloud.githubusercontent.com/assets/1857448/11864993/fc54aaba-a4db-11e5-864d-eef5ba44ab0d.png">

**Comment by haifengkao** [comment]
please use libsqlite3.0.dylib
The sample project worked in Xcode 7.2
