### ISSUE TITLE
mixed Chinese and English text

### ISSUE THREAD

**Issue by kenlo88** [haifengkao/SqliteSubstringSearch#3]
Works marvellously with Chinese text and it is exactly what I want.

But for mixed Chinese and English text, the tokenizer treats every single alphabet as individual token.  FTS in English is therefore not feasible.  Is there a simple way to retain the best of 2 kinds i.e. simple tokenizer for English  (single-byte characters) words + character tokenizer for unicode (multi-byte characters)?

**Comment by haifengkao** [comment]
oh oh. please help me understand it
今天weather is good -> 今 天 weather is good
if you search for keyword `天weather`, you will find the sentence without any problems right?
if you search for keyword `ther`, you will also find the sentence and you don't want this behavior?

**Comment by kenlo88** [comment]
$ cat test.sql
.load ./character
CREATE VIRTUAL TABLE IF NOT EXISTS papers USING fts3(author, document, tokenize=character);
INSERT INTO papers VALUES ('kenlo','（法新社卡拉卡斯1日電） 反對委內瑞拉總統馬杜洛（Nicolas Maduro）的抗議人士今天宣稱');
INSERT INTO papers VALUES ('kenlo','Dear somebody, 反對委內瑞拉總統馬杜洛');
INSERT INTO papers VALUES ('kenlo','Roads and drains in Area 法新社卡拉卡斯1日電');
SELECT author, snippet(papers,'<strong>','</strong>','',-1,20) as snippet from papers where document match 'dear';
$ d:/my/util/sqlite3 t.db < test.sql
kenlo|<strong>D</strong><strong>e</strong><strong>a</strong><strong>r</strong> som<strong>e</strong>bo<strong>d</strong>y, 反對委內瑞
kenlo|<strong>d</strong>s <strong>a</strong>n<strong>d</strong> <strong>d</strong><strong>r</strong><strong>a</strong>ins in <strong>A</strong><strong>r</strong><strong>e</strong>

The second result of the query is not expected, although it matches the {d,e,a,r} combination.

**Comment by haifengkao** [comment]
I see. Please use the [phrase query](https://www.sqlite.org/fts3.html#section_3_1):
`SELECT author, snippet(papers,'','','',-1,20) as snippet from papers where document match '"dear"';`
There are double-quotes around `dear`

**Comment by haifengkao** [comment]
if no further questions, I would like to close this issue
